# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

from pathlib import Path
from tkinter import Tk, Canvas, Entry, Label, PhotoImage, font
from alert_ext import Alert


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


def create_alert_window(medicine_name):
    window = Tk()
    window.geometry("480x217")
    window.configure(bg="#A3CD9E")

    canvas = Canvas(
        window,
        bg="#A3CD9E",
        height=217,
        width=480,
        bd=0,
        highlightthickness=0,
        relief="ridge"
    )
    canvas.place(x=0, y=0)

    image_image_1 = PhotoImage(file=relative_to_assets("image_1.png"))
    canvas.create_image(240.0, 23.0, image=image_image_1)

    image_image_2 = PhotoImage(file=relative_to_assets("image_2.png"))
    canvas.create_image(43.0, 125.0, image=image_image_2)

    image_image_3 = PhotoImage(file=relative_to_assets("image_3.png"))
    canvas.create_image(240.0, 125.0, image=image_image_3)

    entry_image_1 = PhotoImage(file=relative_to_assets("entry_1.png"))
    canvas.create_image(213.0, 123.0, image=entry_image_1)

    custom_font = font.Font(family="Bitter", size=8, weight="bold")

    label_1 = Label(
        window,
        text=medicine_name,
        bg="#FFFFFF",
        fg="#000716",
        font=custom_font
    )
    label_1.place(x=169.0, y=113.0)

    window.resizable(False, False)
    window.mainloop()


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"assets\frame0")

# Gọi class Alert để lấy danh sách thuốc sắp hết hạn
alert = Alert()
for medicine in alert.expiring_medicines:
    create_alert_window(medicine)
    print(medicine)