#
# # This file was generated by the Tkinter Designer by Parth Jadhav
# # https://github.com/ParthJadhav/Tkinter-Designer
#

import json
from tkinter import ttk, messagebox
from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"assets/alert_tracking")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("480x217")
window.configure(bg = "#CFE9C2")


canvas = Canvas(
    window,
    bg = "#CFE9C2",
    height = 217,
    width = 480,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    252.0,
    28.0,
    image=image_image_1
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    240.0,
    147.5,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=47.0,
    y=90.0,
    width=386.0,
    height=113.0
)

canvas.create_text(
    130.0,
    60.0,
    anchor="nw",
    text="THUỐC SẮP HẾT HÀNG",
    fill="#000000",
    font=("Bitter Bold", 20 * -1)
)
columns = ("Name", "Type", "Quantity")
tree = ttk.Treeview(window, columns=columns, show='headings', height=5)

tree.heading("Name", text="Name", anchor="center")
tree.heading("Type", text="Type", anchor="center")
tree.heading("Quantity", text="Quantity", anchor="center")

tree.column("Name", width=80, anchor="center", stretch=True)
tree.column("Type", width=140, anchor="center", stretch=True)
tree.column("Quantity", width=60, anchor="center", stretch=True)

tree.place(x=40, y=90, width=400, height=115)


def load_low_stock_medicines():
    try:
        with open("data/Medicines.json", "r", encoding="utf-8") as file:
            medicines = json.load(file)

        tree.delete(*tree.get_children())

        low_stock_medicines = list(filter(lambda m: int(m["quantity"]) < 20, medicines))
        for medicine in low_stock_medicines:
            tree.insert("", "end", values=(medicine['name'], medicine['type'], medicine['quantity']))

        if not tree.get_children():
            messagebox.showinfo("Thông báo", "Không có thuốc nào dưới 20 đơn vị.")
            window.destroy()
    except Exception as e:
        messagebox.showerror("Lỗi", f"Không thể tải dữ liệu: {str(e)}")

load_low_stock_medicines()

window.resizable(False, False)
window.mainloop()
