import sys

# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

from Tracking_Quantity_EXT import Tracking
from pathlib import Path
import subprocess
# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Button, PhotoImage, ttk


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"assets/tracking")
if len(sys.argv) < 2:
    print("tracking.py was opened directly. Launching main.py...")
    subprocess.Popen(["python", "Main.py"])
    sys.exit()

def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)
def open_script(script_name):
    try:
        # Pass the current window position as arguments
        x_pos = window.winfo_x()
        y_pos = window.winfo_y()
        subprocess.Popen(["python", script_name, str(x_pos), str(y_pos)])
    except Exception as e:
        print(f"Error opening {script_name}: {e}")
    finally:
        window.quit()
        window.destroy()


window = Tk()
try:
    x_pos = int(sys.argv[1])
    y_pos = int(sys.argv[2])
    window.geometry(f"720x512+{x_pos}+{y_pos}")
except (IndexError, ValueError):
    window.geometry("720x512")

window.configure(bg="#FFFFFF")
canvas = Canvas(window, bg="#FFFFFF", height=512, width=720, bd=0, highlightthickness=0, relief="ridge")
canvas.place(x=0, y=0)


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 512,
    width = 720,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    363.0,
    258.5,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    401.5,
    280.0,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    411.0,
    31.0,
    image=image_image_3
)

button_image_2 = PhotoImage(file=relative_to_assets("button_2.png"))
button_tab4 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: open_script("tracking.py"),
    relief="flat"
)
button_tab4.place(x=23, y=392.0, width=56.8125, height=57.1139)

button_image_3 = PhotoImage(file=relative_to_assets("button_3.png"))
button_tab3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: open_script("salequantity.py"),
    relief="flat"
)
button_tab3.place(x=23, y=283, width=56.8125, height=57.1139)

button_image_4 = PhotoImage(file=relative_to_assets("button_4.png"))
button_tab2 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: open_script("adjust.py"),
    relief="flat"
)
button_tab2.place(x=23, y=174, width=56.8125, height=57.1139)

button_image_5 = PhotoImage(file=relative_to_assets("button_5.png"))
button_tab1 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: open_script("home.py"),
    relief="flat"
)
button_tab1.place(x=23, y=65, width=56.8125, height=57.1139)


canvas.create_text(
    221.0,
    111.0,
    anchor="nw",
    text="QUẢN LÝ SỐ LƯỢNG THUỐC",
    fill="#000000",
    font=("Bitter Bold", 25 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    545.0,
    370.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0,
    justify="center"
)
entry_1.place(
    x=503.0,
    y=348.0,
    width=84.0,
    height=42.0,
)

entry_2 = Entry (
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0,
    justify="center"
)
entry_2.place(
    x=165.0,
    y=348.0,
    width=260.0,
    height=42.0,
)

canvas.create_rectangle(
    164.0,
    151.0,
    621.0,
    312.0,
    fill="#FFFFFF",
    outline="")

canvas.create_text(
    474.0,
    326.0,
    anchor="nw",
    text="Số lượng  cập nhật",
    fill="#000000",
    font=("Bitter Bold", 16 * -1)
)

canvas.create_text(
    227.0,
    326.0,
    anchor="nw",
    text="Loại thuốc cập nhật",
    fill="#000000",
    font=("Bitter Bold", 16 * -1)
)

#Tạo bảng treeview
columns = ("Name", "Type", "Quantity")
tree = ttk.Treeview(window, columns=columns, show='headings', height=5)

tree.heading("Name", text="Name", anchor="center")
tree.heading("Type", text="Type", anchor="center")
tree.heading("Quantity", text="Quantity", anchor="center")

tree.column("Name", width=80, anchor="center", stretch=True)
tree.column("Type", width=140, anchor="center", stretch=True)
tree.column("Quantity", width=60, anchor="center", stretch=True)

tree.place(x=162, y=150, width=460, height=165)

#Tạo tracking
tracking = Tracking(entry_medicine = entry_2, entry_quantity = entry_1)
tracking.set_tree(tree)
tracking.display_medicines(tree)

tree.bind("<<TreeviewSelect>>", lambda event: tracking.select_medicine(event, tree))

#Nút giảm
image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    604.0,
    370.0,
    image=image_image_4
)
canvas.tag_bind(image_4, "<Button-1>", lambda event: tracking.update_quantity(-1))

#Nút tăng
image_image_5 = PhotoImage(
    file=relative_to_assets("image_5.png"))
image_5 = canvas.create_image(
    479.0,
    370.0,
    image=image_image_5
)
canvas.tag_bind(image_5, "<Button-1>", lambda event: tracking.update_quantity(1))

#Nút lưu
button_save = Button(
    window,
    text="Lưu",
    font=("Bitter Bold", 16),
    bg="#A3CD9E",
    fg="#000000",
    borderwidth=0,
    highlightthickness=0,
    relief="flat",
    command=tracking.save
)

button_save.place(x=190, y=412, width=180, height=35)

#Cập nhật toàn bộ
button_update_all = Button(
    window,
    text="Cập nhật toàn bộ",
    font=("Bitter Bold", 16),
    bg="#A3CD9E",
    fg="#000000",
    borderwidth=0,
    highlightthickness=0,
    relief="flat",
    command=tracking.update_all
)

button_update_all.place(x=410, y=412, width=180, height=35)

window.resizable(False, False)
window.mainloop()
